# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hyperionnet

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Clear(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Clear()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClear(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Clear
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Clear
    def Priority(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ClearStart(builder):
    builder.StartObject(1)

def Start(builder):
    ClearStart(builder)

def ClearAddPriority(builder, priority):
    builder.PrependInt32Slot(0, priority, 0)

def AddPriority(builder, priority):
    ClearAddPriority(builder, priority)

def ClearEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClearEnd(builder)
