# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hyperionnet

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Register(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Register()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRegister(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Register
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Register
    def Origin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Register
    def Priority(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RegisterStart(builder):
    builder.StartObject(2)

def Start(builder):
    RegisterStart(builder)

def RegisterAddOrigin(builder, origin):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(origin), 0)

def AddOrigin(builder, origin):
    RegisterAddOrigin(builder, origin)

def RegisterAddPriority(builder, priority):
    builder.PrependInt32Slot(1, priority, 0)

def AddPriority(builder, priority):
    RegisterAddPriority(builder, priority)

def RegisterEnd(builder):
    return builder.EndObject()

def End(builder):
    return RegisterEnd(builder)
